### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by heniu1985** [heniu1985/taurus-mercatus#1]
Why in back_to_file() function is following error:

Traceback (most recent call last):
  File "/home/heniu/Programowanie/Projekty/taurus-mercatus/taurus.py", line 361, in <module>
    main()
  File "/home/heniu/Programowanie/Projekty/taurus-mercatus/taurus.py", line 356, in main
    back_to_file(path, x)
  File "/home/heniu/Programowanie/Projekty/taurus-mercatus/taurus.py", line 139, in back_to_file
    keys = list_of_dicts[0].keys()
IndexError: list index out of range

**Comment by heniu1985** [comment]
Done.
